version: '3.8'
services:
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - service
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blockbooks
  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
  service:
    build: .
    volumes:
      - .:/app
    ports:
      - 2411:2411
    depends_on:
      - postgres
      - redis
    restart: on-failure
    environment:
      PORT: 2411
      PG_HOST: postgres
      PG_USERNAME: root
      PG_PASSWORD: root
      PG_DATABASE: blockbooks
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: npm run start:dev
